package es.uvigo.ei.sing.s2p.aibench.operations;

import static es.uvigo.ei.sing.s2p.aibench.operations.dialogs.AbstractCsvInputDialog.CSV_FORMAT;
import static es.uvigo.ei.sing.s2p.aibench.operations.dialogs.AbstractCsvInputDialog.CSV_FORMAT_DESCRIPTION;
import static es.uvigo.ei.sing.s2p.core.io.samespots.SameSpotsCsvDirectoryLoader.loadDirectory;

import java.io.File;
import java.util.List;

import es.uvigo.ei.aibench.core.operation.annotation.Direction;
import es.uvigo.ei.aibench.core.operation.annotation.Operation;
import es.uvigo.ei.aibench.core.operation.annotation.Port;
import es.uvigo.ei.sing.commons.csv.entities.CsvFormat;
import es.uvigo.ei.sing.s2p.aibench.datatypes.SameSpotsAnalysisDatatype;
import es.uvigo.ei.sing.s2p.core.entities.SameSpotsThrehold;
import es.uvigo.ei.sing.s2p.core.entities.Sample;

@Operation(
	name = "Import SameSpots CSV files", 
	description = "Imports a set of CSV files containing spots data obtained with Progenesis SameSpots."
)
public class ImportSameSpotsCsvFiles {
	private static final String DEFAULT_P = "1";
	private static final String DEFAULT_FOLD = "0";

	private File directory;
	private double pValue;
	private double fold;
	private CsvFormat csvFormat;

	@Port(
		direction = Direction.INPUT, 
		name = "SameSpots CSV directory",
		description = "The directory containing the CSV files generated by the "
			+ "Protenesis SameSpots software. Please, note that you must "
			+ "select a directory and not the individual files.",
		order = 1,
		extras="selectionMode=directories"
	)
	public void setCsvFile(File directory) {
		this.directory = directory;
	}
	
	@Port(
		direction = Direction.INPUT, 
		name = "p-value", 
		defaultValue = DEFAULT_P,
		description = "The maximum p-value allowed for spots to be loaded. "
			+ "Spots within a higher p-value will not be loaded.",
		order = 2
	)
	public void setPValue(double pValue) {
		this.pValue = pValue;
	}
	
	@Port(
		direction = Direction.INPUT, 
		name = "Fold",
		defaultValue = DEFAULT_FOLD,
		description = "The minimum fold allowed for spots to be loaded. "
			+ "Spots within a lower fold will not be loaded.",
		order = 3
	)
	public void setFold(double fold) {
		this.fold = fold;
	}

	@Port(
		direction = Direction.INPUT, 
		name = CSV_FORMAT,
		description = CSV_FORMAT_DESCRIPTION,
		order = 4
	)
	public void setCsvFormat(CsvFormat csvFormat) {
		this.csvFormat = csvFormat;
	}	
	
	@Port(direction = Direction.OUTPUT, order = 5)
	public SameSpotsAnalysisDatatype loadData() throws Exception {
		SameSpotsThrehold threshold = new SameSpotsThrehold(pValue, fold);
	
		List<Sample> samples = loadDirectory(directory, threshold, csvFormat);

		return new SameSpotsAnalysisDatatype(directory, threshold, samples);
	}
}
